name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: deploy
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: PHP
      run: php -v
    
